-- Copyright The OpenTelemetry Authors
-- SPDX-License-Identifier: Apache-2.0

-- Enable pg_stat_statements in the default postgres database
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- Create application user
CREATE USER astronomy_user WITH PASSWORD 'astronomy_password';

-- Create application database
CREATE DATABASE astronomy_db OWNER astronomy_user;

-- Create monitoring user with pg_monitor role (visibility on all databases and schemas)
CREATE USER monitoring_user WITH PASSWORD 'monitoring_password';
GRANT pg_monitor TO monitoring_user;

-- Switch to the application database
\connect astronomy_db

-- Enable pg_stat_statements in the application database
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- Accounting Service: create a schema
CREATE SCHEMA accounting;
GRANT USAGE ON SCHEMA accounting TO astronomy_user;

-- Accounting Service: create tables
CREATE TABLE accounting."order" (
    order_id TEXT PRIMARY KEY
);

CREATE TABLE accounting.shipping (
    shipping_tracking_id TEXT PRIMARY KEY,
    shipping_cost_currency_code TEXT NOT NULL,
    shipping_cost_units BIGINT NOT NULL,
    shipping_cost_nanos INT NOT NULL,
    street_address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    zip_code TEXT,
    order_id TEXT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES accounting."order"(order_id) ON DELETE CASCADE
);

CREATE TABLE accounting.orderitem (
    item_cost_currency_code TEXT NOT NULL,
    item_cost_units BIGINT NOT NULL,
    item_cost_nanos INT NOT NULL,
    product_id TEXT NOT NULL,
    quantity INT NOT NULL,
    order_id TEXT NOT NULL,
    PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES accounting."order"(order_id) ON DELETE CASCADE
);

-- Accounting Service: grant permission to schema
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA accounting TO astronomy_user;

-- Product Review Service: create a schema
CREATE SCHEMA reviews;
GRANT USAGE ON SCHEMA reviews TO astronomy_user;

-- Product Review Service: create tables
CREATE TABLE reviews.productreviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(16) NOT NULL,
    username VARCHAR(64) NOT NULL,
    description VARCHAR(1024),
    score NUMERIC(2,1) NOT NULL
);

-- Product Review Service: create index for product_id lookups
CREATE INDEX product_id_index ON reviews.productreviews (product_id);

-- Product Review Service: grant permission to schema
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA reviews TO astronomy_user;

-- Product Review Service:  add product review data
INSERT INTO reviews.productreviews (product_id, username, description, score)
VALUES
    ('OLJCESPC7Z', 'stargazer_mike', '初心者向け望遠鏡として最高！セットアップも簡単で、月や明るい惑星がくっきり見えます。天文を始めたばかりの方に強くおすすめします。', '4.5'),
    ('OLJCESPC7Z', 'nightskylover', 'この価格でこの性能は驚き。木星の衛星もはっきり見えました。気軽に楽しみたい方に最適な一台です。', '4.0'),
    ('OLJCESPC7Z', 'beginner_astro', '手動操作に慣れるまで少し時間がかかりますが、慣れると楽しい！オリオン星雲を初めて見たときは感動しました。コスパは良いと思います。', '3.5'),
    ('OLJCESPC7Z', 'celestial_explorer', 'キャンプに持ち出せる軽さが魅力。このサイズとは思えないほど良く見えます。どこへでも持っていけるのが最高です。', '4.0'),
    ('OLJCESPC7Z', 'telescope_fan', '本格的な性能ではありませんが、子ども向けや初心者にはぴったり。子どもたちが月を見るのを楽しんでいます。家族で使えるおすすめの一台。', '3.0'),

    ('66VCHSJNUP', 'tech_astro', 'StarSenseアプリは革命的！天体を見つけるのがびっくりするほど簡単になりました。初心者にとってゲームチェンジャーな望遠鏡です。', '5.0'),
    ('66VCHSJNUP', 'app_user', 'スマートフォン連携が完璧に動作します。夜空の探索がこんなに楽しくなるとは。価格分の価値は十分あります。', '4.5'),
    ('66VCHSJNUP', 'innovator_john', 'セットアップが簡単で、アプリのチュートリアルも分かりやすい。唯一の不満はスマホのバッテリー消費が早いこと。', '4.0'),
    ('66VCHSJNUP', 'clear_skies', 'ついに星空の謎解きから解放されました。リアルタイムの位置精度は驚異的。天文を始めたい方に全力でおすすめします。', '5.0'),
    ('66VCHSJNUP', 'gadget_geek', 'アプリがまるで専属天文ガイドのよう。光学性能も非常に高く、大満足の一台です。', '4.5'),

    ('1YMWWN1N4O', 'solar_viewer', 'Solar Safeフィルターで安心して太陽観測できます。先日の部分日食でも大活躍しました。太陽観測用に最高の一台です。', '5.0'),
    ('1YMWWN1N4O', 'eclipse_chaser', 'コンパクトで携帯しやすく、日食イベントに最適。付属バックパックも便利。太陽の見え方が驚くほどクリアです。', '4.5'),
    ('1YMWWN1N4O', 'travel_astro', '太陽観測用の旅行スコープとして優秀。双眼鏡よりはるかに高倍率で観測できます。太陽ファン必携の一品です。', '4.0'),
    ('1YMWWN1N4O', 'sun_gazer', '安全機能とクリアな視野に大満足。家族と一緒に太陽を観察するのがとても簡単になりました。専用太陽スコープとして大変良い価値があります。', '5.0'),
    ('1YMWWN1N4O', 'safe_viewer', 'ISO準拠フィルターで安心感抜群。安全な太陽観測向けに丁寧に設計された製品です。教育目的にも強くおすすめします。', '4.5'),

    ('L9ECAV7KIM', 'clean_optics', 'あらゆる光学機器のメンテナンスに欠かせないキット。ブラシとワイプが残留物なく完璧に機能します。レンズがこれほどきれいになるとは！', '5.0'),
    ('L9ECAV7KIM', 'photog_pro', 'カメラマンや望遠鏡ユーザーには必須品。埃や指紋を安全に除去できる高品質なクリーニングセットです。', '4.5'),
    ('L9ECAV7KIM', 'daily_cleaner', '双眼鏡・カメラレンズ・スマホ画面にも使えます。効果的でやさしい使い心地。汎用性の高いクリーニングキットです。', '4.0'),
    ('L9ECAV7KIM', 'tech_maintenance', 'コスパ最高。様々なクリーニングオプションでどんな需要にも対応。高価な機材をいつも最良の状態に保てます。', '5.0'),
    ('L9ECAV7KIM', 'sharp_view', '使用後は望遠鏡の見え方が格段に向上しました。クリーニング液とクロスの品質が素晴らしい。強くおすすめします。', '4.5'),

    ('2ZYFJ3GM2N', 'bird_watcher', 'バードウォッチングに最適な明るさとクリアさ。EDガラスのおかげで微細な羽模様まで確認できます。', '5.0'),
    ('2ZYFJ3GM2N', 'nature_lover', '自然観察に最高の双眼鏡。近距離合焦が優れており、近くの野生動物もしっかり見えます。手に持ちやすい設計も◎。', '4.5'),
    ('2ZYFJ3GM2N', 'hiker_guy', '軽量で丈夫、ハイキングのお供に最適。広い視野角が特に優秀。アウトドア好きには強くおすすめします。', '4.0'),
    ('2ZYFJ3GM2N', 'stadium_fan', 'スポーツ観戦に持参して大正解。様々な光量条件でも安定したパフォーマンスを発揮します。', '4.0'),
    ('2ZYFJ3GM2N', 'outdoor_adventurer', '優れた品質と光学性能。頑丈な作りで鮮明な像を提供。あらゆるアウトドア活動への投資として最適です。', '4.5'),

    ('0PUK6V6EV0', 'astro_photog', '惑星撮影の次のステップに最適なイメージャー。色の再現性が素晴らしく、既存の望遠鏡にも簡単に接続できます。', '5.0'),
    ('0PUK6V6EV0', 'planet_shooter', 'ついに土星と木星の見事な画像が撮れました！NexImage 10で天体撮影が身近になりました。天文撮影入門者に最適。', '4.5'),
    ('0PUK6V6EV0', 'imager_pro', 'この価格帯では優秀な解像度と色再現性。惑星撮影を始めたい方に最適なソリューションです。', '4.0'),
    ('0PUK6V6EV0', 'space_artist', 'このイメージャーで捉えられる細部の描写が驚異的。各種ソフトウェアとの相性も◎。本格的な惑星観測者には必須アイテム。', '5.0'),
    ('0PUK6V6EV0', 'digital_sky', '惑星撮影の入門機として堅実な選択。セットアップも簡単で、美しい惑星画像が撮れます。', '4.5'),

    ('LS4PSXUNUM', 'night_walker', '天文セッション中の夜間視力維持に最適な赤色ライト。ハンドウォーマーも予想外に便利です。実用的な多機能デバイスです。', '5.0'),
    ('LS4PSXUNUM', 'star_party_goer', '星空観察会に欠かせないアイテム。赤色モードが目にやさしく、モバイルバッテリー機能も超便利。大のお気に入りです！', '4.5'),
    ('LS4PSXUNUM', 'camper_chris', 'キャンプや夜間ウォーキングに最高。ハンドウォーマー機能は寒い夜に大活躍。強くおすすめします。', '4.5'),
    ('LS4PSXUNUM', 'emergency_kit', '防災セットにも最適な多機能ツール。赤色ライトが便利で、モバイルバッテリーでスマホも充電可能。優れたデザインです。', '4.0'),
    ('LS4PSXUNUM', 'astro_accessory', '天文家なら全員必携。赤色ライトはもちろん、ハンドウォーマーとモバイルバッテリーで驚くほど実用的。最高レベルのアクセサリーです。', '5.0'),

    ('9SIQT8TOJO', 'deep_sky_master', 'RASA V2は深宇宙撮影者の夢を叶える鏡筒。f/2.2の超高速光学系で露出時間が劇的に短縮。天体撮影への最高の投資でした。', '5.0'),
    ('9SIQT8TOJO', 'pro_astro', '広視野天体撮影での性能は信じがたいほど。短焦点のおかげでガイディングも楽になります。驚異的な結果が得られます。', '5.0'),
    ('9SIQT8TOJO', 'imaging_guru', 'この鏡筒はまさに怪物級！高速光学系で短時間に多くのデータが取れます。深宇宙撮影を本気でやるならこれ一択です。', '4.5'),
    ('9SIQT8TOJO', 'advanced_scope', 'この品質とスピードに支払う価値は十分あります。これまでで最もシャープで鮮やかな画像が撮れるようになりました。', '5.0'),
    ('9SIQT8TOJO', 'precision_optics', 'このRASAの設計技術は卓越しています。淡い天体の撮影効率が驚くほど高い。本格的な天体撮影家向けのハイエンド機材です。', '4.5'),

    ('6E92ZMYYFZ', 'solar_safety', '8インチ望遠鏡での安全な太陽観測に欠かせないフィルター。ベルクロストラップで確実に固定。安心して太陽を観察できます。', '5.0'),
    ('6E92ZMYYFZ', 'telescope_upgrade', '私のセットアップへの完璧な追加品。ISO準拠が重要なポイント。安全に太陽を見たい方に強くおすすめします。', '4.5'),
    ('6E92ZMYYFZ', 'safe_sun_gazer', '簡単に装着でき、安全で鮮明な太陽の見え方を提供。品質も優秀。太陽観測ファンには必須のアクセサリーです。', '5.0'),
    ('6E92ZMYYFZ', 'filter_fan', '8インチスコープに完璧にフィット。誤って外れる心配もなし。目と機材を守る優れた製品です。', '4.5'),
    ('6E92ZMYYFZ', 'eclipse_ready', '日食に向けて購入しましたが、完璧にフィットしました。視野も安全で素晴らしい。とても満足しています。', '5.0'),

    ('HQTGWGPNH4', 'history_buff', '歴史的天文思想への魅力的な入門書。内容は非常に示唆に富んでいます。科学史に興味がある方には必読の一冊です。', '5.0'),
    ('HQTGWGPNH4', 'bookworm_astro', '美しく提示された歴史的文書。何世紀も前に彗星がどのように理解されていたかを知るのは驚きです。天文学ライブラリーへの貴重な追加です。', '4.5'),
    ('HQTGWGPNH4', 'ancient_texts', '非常にユニークで興味深い読み物。歴史的文脈が魅力的で、天体現象に対する独自の視点を提供してくれます。', '4.0'),
    ('HQTGWGPNH4', 'celestial_history', '歴史的天文学が大好きで、この本はその期待に応えてくれました。過去の信仰への窓を開いてくれる、学者にも強くおすすめできる一冊です。', '5.0'),
    ('HQTGWGPNH4', 'rare_find', '天文学史愛好家にとって本当に特別な本。古代占星術師に関する詳細が非常に興味深い。より深い理解を求める方にぴったりです。', '4.5');

-- Product Catalog Service: create a schema
CREATE SCHEMA catalog;
GRANT USAGE ON SCHEMA catalog TO astronomy_user;

-- Product Catalog Service: create tables
CREATE TABLE catalog.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    picture TEXT,
    price_currency_code TEXT NOT NULL,
    price_units BIGINT NOT NULL,
    price_nanos INT NOT NULL,
    categories TEXT
);

-- Product Catalog Service: grant permission to schema
GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO astronomy_user;

-- Product Catalog Service: add product data
INSERT INTO catalog.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories)
VALUES
    ('OLJCESPC7Z', 'ナショナルパーク財団 エクスプロラスコープ', 'NPF エクスプロラスコープ60AZは、持ち運びやすい手動経緯台式屈折望遠鏡。月・惑星・星団、オリオン星雲やアンドロメダ銀河などの明るい深宇宙天体を観望できます。', 'NationalParkFoundationExplorascope.jpg', 'USD', 101, 960000000, 'telescopes'),
    ('66VCHSJNUP', 'スターセンス エクスプローラー 屈折望遠鏡', 'スマートフォンで夜空を解析し、リアルタイムに位置を算出する世界初の望遠鏡。初心者に優しいアプリのインターフェースと詳細なチュートリアルで、まるで専属ガイドと夜空を旅するような体験が楽しめます。', 'StarsenseExplorer.jpg', 'USD', 349, 950000000, 'telescopes'),
    ('1YMWWN1N4O', 'エクリプスマート トラベル屈折望遠鏡', '移動先での白色光太陽観測に特化したコンパクトな太陽望遠鏡。ISO準拠のフルアパーチャーガラスフィルターで安全に太陽を観察できます。三脚・20mmアイピース・ナイロンバックパック付属。家族全員で皆既日食・部分日食を楽しめます。', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 129, 950000000, 'telescopes,travel'),
    ('L9ECAV7KIM', 'レンズクリーニングキット', 'レンズブラシ・クリーニングワイプ・洗浄液＆クロスのセット。望遠鏡・双眼鏡・カメラレンズ・スマートフォン画面など、あらゆる光学面の埃・汚れ・指紋を安全に除去します。', 'LensCleaningKit.jpg', 'USD', 21, 950000000, 'accessories'),
    ('2ZYFJ3GM2N', 'ルーフ型双眼鏡', 'トレイル、スタジアム、アリーナなど様々な場面で活躍する万能双眼鏡。自然観察やバードウォッチングに最適で、EDガラスにより微細なフィールドマーキングも鮮明に捉えられます。最短合焦距離2m対応。', 'RoofBinoculars.jpg', 'USD', 209, 950000000, 'binoculars'),
    ('0PUK6V6EV0', '惑星カラーイメージャー', '新しい望遠鏡を手に入れて土星や木星を観察した。次のステップは撮影だ。でも、どこから始めれば？NexImage 10 惑星カラーイメージャーはその最適な答えです。', 'SolarSystemColorImager.jpg', 'USD', 175, 0, 'accessories,telescopes'),
    ('LS4PSXUNUM', 'レッドフラッシュライト（3イン1）', '3モード赤色LEDライト・ハンドウォーマー・モバイルバッテリーの3機能を搭載。天文観察、夜間ウォーキング、野生動物観察に最適。IPX4防水設計。', 'RedFlashlight.jpg', 'USD', 57, 80000000, 'accessories,flashlights'),
    ('9SIQT8TOJO', '光学鏡筒アセンブリ（RASA V2）', 'f/2.2の高速広視野光学系で深宇宙天体撮影が手軽に。DSLR・天文用CCDカメラに対応。露出時間を大幅短縮でき、赤道儀の精密追尾が不要になる場合もあります。', 'OpticalTubeAssembly.jpg', 'USD', 3599, 0, 'accessories,telescopes,assembly'),
    ('6E92ZMYYFZ', 'ソーラーフィルター（8インチ用）', '8インチ望遠鏡向けEclipSmartソーラーフィルター。2本のベルクロストラップと4つの自己接着ベルクロパッドで確実に固定。ISO準拠の安全な太陽観測を提供します。', 'SolarFilter.jpg', 'USD', 69, 950000000, 'accessories,telescopes'),
    ('HQTGWGPNH4', '彗星の書', '16世紀フランドル地方で匿名作成された彗星論。カッセル大学図書館所蔵。プトレマイオスらの占星術師による彗星の意味を解説した歴史的天文書。', 'TheCometBook.jpg', 'USD', 0, 990000000, 'books');